# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
    - name: bovine
      run: |
        cd bovine
        poetry install
        poetry run flake8
        poetry run pytest
# Github does not support hypercorn...
#     - name: bovine_store
#       run: |
#         cd bovine_store
#         poetry install
#         poetry run flake8
#         poetry run pytest
#     - name: bovine_user
#       run: |
#         cd bovine_user
#         poetry install
#         poetry run flake8
#         poetry run pytest
#     - name: bovine_fedi
#       run: |
#         cd bovine_fedi
#         poetry install
#         poetry run flake8
#         poetry run pytest
#     - name: tests
#       run: |
#         cd tests
#         poetry install
#         poetry run flake8
#         poetry run pytest
